# Generated by Django 5.1.2 on 2024-10-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(blank=True, max_length=200, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('Discription', models.TextField(blank=True, max_length=200, null=True)),
                ('Country_of_Origin', models.CharField(blank=True, max_length=200, null=True)),
                ('Manufactured_By', models.CharField(blank=True, max_length=200, null=True)),
                ('Product_Image1', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('Product_Image2', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('Product_Image3', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
