# Generated by Django 5.1.2 on 2024-10-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture_app', '0002_product_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_db',
            name='MRP',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
