# Generated by Django 5.1.2 on 2024-11-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0002_signup_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Total_Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
