# Generated by Django 5.1.2 on 2024-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0003_cart_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_db',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart_db',
            name='Total_Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
