# Generated by Django 5.1.2 on 2024-11-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0004_alter_cart_db_price_alter_cart_db_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_db',
            name='Cart_image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart_images'),
        ),
    ]
