# Generated by Django 5.1.2 on 2024-11-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0005_cart_db_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_db',
            name='Cart_image',
        ),
    ]
