# Generated by Django 5.1.2 on 2024-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0007_order_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_db',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
