# Generated by Django 5.1.2 on 2024-11-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0008_alter_order_db_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_db',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_images'),
        ),
    ]
